### ISSUE TITLE
help

### ISSUE THREAD

**Issue by HarlanZhou** [tjiagoM/spatio-temporal-brain#18]
how to create my custiom dataset, if i use this model to training

**Comment by tjiagoM** [comment]
Hi! 

You can see the code I created to load data from the uk biobank and human connectome project (HCP) here: https://github.com/tjiagoM/spatio-temporal-brain/blob/master/datasets.py

You will probably need to know how data loading works with pytorch geometric (https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html), before looking to this module.


Hope this helps!

**Comment by HarlanZhou** [comment]
> Hi!
> 
> You can see the code I created to load data from the uk biobank and human connectome project (HCP) here: https://github.com/tjiagoM/spatio-temporal-brain/blob/master/datasets.py
> 
> You will probably need to know how data loading works with pytorch geometric (https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html), before looking to this module.
> 
> Hope this helps!

Could this model be used in another way to build data sets from documents
```python
from torch_geometric.data import Data, DataLoader

data_list = [Data(...), ..., Data(...)]
loader = DataLoader(data_list, batch_size=32)
```

**Comment by tjiagoM** [comment]
Hi again! Sorry, but I'm not sure I follow your question and how the code relates to it.
