### ISSUE TITLE
data management 

### ISSUE THREAD

**Issue by miladalipour99** [tjiagoM/spatio-temporal-brain#19]
Hi,
Nice work and I highly appreciate it. Can you please guide about how to place data in directory if someone doesn't have access to ADNI due to region limitations and wants to use their own dataset, and also is it possible to access to your preprocessed  data.
I am waiting for your kind reply.
Thanks

**Comment by tjiagoM** [comment]
Hi! Thanks for your interest in our work!

You can see the code I created to load data from the uk biobank and human connectome project (HCP) here: https://github.com/tjiagoM/spatio-temporal-brain/blob/master/datasets.py

You will probably need to know how data loading works with pytorch geometric (https://pytorch-geometric.readthedocs.io/en/latest/notes/create_dataset.html), before looking to this module.

Hope this helps!


P.S.: I'm currently quite busy in answering to a rebuttal round of a journal at which we submitted this work. As a consequence, I've been changing the code in a branch named `dev`. As the paper is not yet accepted and includes some changes which are not in the paper I'm not putting this in the main branch for now. However, if you are curious, feel free to check: https://github.com/tjiagoM/spatio-temporal-brain/tree/dev
